export function initAmbientScene(){
  if(document.querySelector('.ambient-scene')) return;
  const scene=document.createElement('div');
  scene.className='ambient-scene';
  scene.setAttribute('aria-hidden','true');
  scene.innerHTML='<canvas id="ambientCanvas"></canvas><svg class="ambient-svg" viewBox="0 0 1200 800" preserveAspectRatio="none"><circle class="ambient-ring ring-a" cx="980" cy="170" r="150"></circle><circle class="ambient-ring ring-b" cx="980" cy="170" r="220"></circle><path class="ambient-line line-a" d="M-100 650 L500 50 L1300 760"></path><path class="ambient-line line-b" d="M-150 720 L560 120 L1350 690"></path></svg>';
  document.body.prepend(scene);
  const canvas=scene.querySelector('#ambientCanvas'),ctx=canvas.getContext('2d',{alpha:true});
  const reduced=matchMedia('(prefers-reduced-motion: reduce)'),touch=matchMedia('(pointer: coarse)').matches;
  const pointer={x:0,y:0,active:false},particles=[],sparks=[];let w=0,h=0,dpr=1,raf=0,last=0;
  const cfg={accent:'rgba(229,9,32,.34)',particle:'rgba(229,9,32,.62)',grid:'rgba(229,9,32,.055)'};
  function resize(){w=innerWidth;h=innerHeight;dpr=Math.min(devicePixelRatio||1,touch?1.25:1.5);canvas.width=Math.floor(w*dpr);canvas.height=Math.floor(h*dpr);canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0);particles.length=0;const n=touch?Math.min(38,Math.max(18,Math.round(w*h/36000))):Math.min(72,Math.max(28,Math.round(w*h/24000)));for(let i=0;i<n;i++)particles.push({x:Math.random()*w,y:Math.random()*h,vx:(Math.random()-.5)*.22,vy:(Math.random()-.5)*.22,r:Math.random()*1.5+.5,a:Math.random()*.45+.2})}
  function spark(x,y,n=5){const limit=touch?18:34;for(let i=0;i<n&&sparks.length<limit;i++){const a=Math.random()*Math.PI*2,s=Math.random()*1.5+.5;sparks.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:1,size:Math.random()*1.5+.6})}}
  function draw(t){if(document.hidden){raf=requestAnimationFrame(draw);return}if(t-last<(touch?33:20)){raf=requestAnimationFrame(draw);return}last=t;ctx.clearRect(0,0,w,h);ctx.strokeStyle=cfg.grid;ctx.lineWidth=1;ctx.beginPath();const step=touch?90:70;for(let x=0;x<=w;x+=step){ctx.moveTo(x,0);ctx.lineTo(x,h)}for(let y=0;y<=h;y+=step){ctx.moveTo(0,y);ctx.lineTo(w,y)}ctx.stroke();const g=ctx.createRadialGradient(w*.72,h*.28,0,w*.72,h*.28,Math.max(w,h)*.75);g.addColorStop(0,cfg.accent);g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);for(const p of particles){p.x+=p.vx;p.y+=p.vy;if(p.x<-10)p.x=w+10;if(p.x>w+10)p.x=-10;if(p.y<-10)p.y=h+10;if(p.y>h+10)p.y=-10;let r=p.r;if(pointer.active&&!touch){const dx=pointer.x-p.x,dy=pointer.y-p.y,d=dx*dx+dy*dy;if(d<9000)r+=(1-d/9000)*1.8}ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fillStyle=cfg.particle;ctx.globalAlpha=p.a;ctx.fill();ctx.globalAlpha=1}if(pointer.active&&!touch){ctx.strokeStyle=cfg.accent;ctx.lineWidth=.7;ctx.beginPath();for(const p of particles){const dx=pointer.x-p.x,dy=pointer.y-p.y;if(dx*dx+dy*dy<7000){ctx.moveTo(p.x,p.y);ctx.lineTo(pointer.x,pointer.y)}}ctx.stroke()}for(let i=sparks.length-1;i>=0;i--){const s=sparks[i];s.x+=s.vx;s.y+=s.vy;s.life-=.045;if(s.life<=0){sparks.splice(i,1);continue}ctx.globalAlpha=s.life;ctx.fillStyle=cfg.particle;ctx.fillRect(s.x,s.y,s.size,s.size);ctx.globalAlpha=1}raf=requestAnimationFrame(draw)}
  resize();addEventListener('resize',resize,{passive:true});addEventListener('pointermove',e=>{if(touch)return;pointer.x=e.clientX;pointer.y=e.clientY;pointer.active=true;if(Math.random()<.025)spark(e.clientX,e.clientY,1)},{passive:true});addEventListener('pointerleave',()=>pointer.active=false,{passive:true});addEventListener('blur',()=>pointer.active=false);document.addEventListener('click',e=>{if(!touch)spark(e.clientX,e.clientY,6)});if(!reduced.matches)raf=requestAnimationFrame(draw);else draw(0);
}