import { loadCollection } from './data.js?v=p5r-modules-20260917-7';

const pageMap={characters:'characters',personas:'personas',shadows:'shadows',palaces:'palaces',confidants:'confidants',skills:'skills',items:'items',guide:'guide'};
function escapeHtml(value){return String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');}
function currentId(){return document.body.dataset.id||new URLSearchParams(window.location.search).get('id');}
function renderRankBox(rank){const ability=rank?.ability||'No new ability';const effect=rank?.effect||'No effect information available.';return `<div class="rank-content"><div class="rank-label">Rank ${escapeHtml(rank?.rank??'')}</div><p><strong>${escapeHtml(ability)}</strong></p><p>${escapeHtml(effect)}</p></div>`;}
function renderConfidants(data){const cards=data.map((c,ci)=>{const ranks=c.ranks??[];const first=ranks[0]??{rank:1,effect:'No rank data available.'};const stars=ranks.map((r,i)=>`<button class="rank-star${i===0?' active':''}" type="button" data-confidant="${ci}" data-rank-index="${i}" aria-label="${escapeHtml(c.name)} Rank ${escapeHtml(r.rank??i+1)}">★</button>`).join('');return `<section class="confidant-rank-card" data-confidant-card="${ci}"><header class="confidant-heading"><h2>${escapeHtml(c.name)}</h2><p><strong>Arcana:</strong> ${escapeHtml(c.arcana)}</p></header><div class="rank-progress">${stars}</div><div class="selected-rank" data-rank-display="${ci}">${renderRankBox(first)}</div></section>`;}).join('');return `<div class="breadcrumb"><a href="../index.html">Home</a> <span>›</span> <span>Confidants</span> <span>›</span> <strong>Rank-Up List</strong></div><h1>Confidant Rank-Up List</h1><p>Select a star to view the ability and effect for that Rank.</p><div class="confidant-rank-list">${cards}</div>`;}
function setupConfidantInteractions(target,data){target.querySelectorAll('.rank-star').forEach(b=>b.addEventListener('click',()=>{const ci=Number(b.dataset.confidant),ri=Number(b.dataset.rankIndex),card=target.querySelector(`[data-confidant-card="${ci}"]`),display=target.querySelector(`[data-rank-display="${ci}"]`),rank=data[ci]?.ranks?.[ri];if(!card||!display||!rank)return;card.querySelectorAll('.rank-star').forEach((s,i)=>s.classList.toggle('active',i<=ri));display.innerHTML=renderRankBox(rank);}));}
function renderCharacterList(data){const selected=data.find(c=>c.id===currentId());if(selected)return renderCharacterDetail(selected);const cards=data.map(c=>`<article class="entity-link"><div><h2>${escapeHtml(c.name)}</h2><p>${escapeHtml(c.role)}</p></div><a href="characters/${encodeURIComponent(c.id)}.html">View Character</a></article>`).join('');return `<div class="breadcrumb"><a href="../index.html">Home</a> <span>›</span> <strong>Characters</strong></div><h1>Characters</h1><p>Main Persona 5 Royal characters.</p><div class="entity-list">${cards}</div>`;}
function renderCharacterDetail(c){const personaPage=c.personaId?`../personas/${encodeURIComponent(c.personaId)}.html`:'';return `<div class="breadcrumb"><a href="../../index.html">Home</a> <span>›</span> <a href="../characters.html">Characters</a> <span>›</span> <strong>${escapeHtml(c.name)}</strong></div><article class="character-detail"><h1>${escapeHtml(c.name)}</h1><p><strong>Real Name:</strong> ${escapeHtml(c.realName||c.name)}</p><p><strong>Age:</strong> ${escapeHtml(c.age)}</p><p><strong>Role:</strong> ${escapeHtml(c.role)}</p><p><strong>Arcana:</strong> ${escapeHtml(c.arcana)}</p><p><strong>Birthday:</strong> ${escapeHtml(c.birthday)}</p><p><strong>Occupation:</strong> ${escapeHtml(c.occupation)}</p><p><strong>Affiliation:</strong> ${escapeHtml(c.affiliation)}</p><section><h2>Biography</h2><p>${escapeHtml(c.bio)}</p></section>${c.personaId?`<section class="character-persona-link"><h2>Persona</h2><a href="${personaPage}">${escapeHtml(c.personaName)}</a><p>${escapeHtml(c.personaRole)}</p></section>`:''}</article>`;}
function skillGroup(title,items,cls=''){if(!items?.length)return '';return `<section class="persona-skill-group ${cls}"><h3>${title}</h3><ul>${items.map(s=>`<li>${escapeHtml(s)}</li>`).join('')}</ul></section>`;}
const personaOrigins={
  arsene:"Arsène awakens as Joker's first Persona during his confrontation with Kamoshida's Shadow. When Joker rejects Kamoshida's control and embraces his own rebellious will, Arsène appears and answers his call.",
  zorro:"Zorro awakens as Morgana's Persona when Morgana fully commits to the Phantom Thieves and confronts the distorted reality surrounding Kamoshida's Palace.",
  'captain-kidd':"Captain Kidd awakens when Ryuji confronts his past with Kamoshida and refuses to let his anger and guilt define him. His rebellion becomes the power that summons his Persona.",
  carmen:"Carmen awakens when Ann rejects Kamoshida's attempts to control and exploit her. By accepting her own anger and choosing to fight back, Ann manifests Carmen.",
  goemon:"Goemon awakens when Yusuke accepts the truth about his relationship with Madarame and turns his desire to expose that corruption into an act of rebellion.",
  johanna:"Johanna awakens when Makoto stops allowing the expectations of others to dictate her choices. Her decision to act on her own will brings forth her Persona.",
  necronomicon:"Necronomicon is Futaba's Persona, awakened after she confronts the distorted memories and guilt surrounding her mother's death and begins accepting the truth about herself.",
  milady:"Milady awakens when Haru rebels against her father's plans for her future and decides to take control of her own life. Her awakening reflects her determination to choose her own path.",
  'robin-hood':"Robin Hood is Akechi's initial Persona and is tied to the heroic identity he presents to the public. Its role becomes more complicated as the truth behind Akechi's actions is revealed.",
  cendrillon:"Cendrillon awakens when Kasumi faces the truth she has been avoiding and accepts her own identity. Her awakening marks her decision to move forward rather than continue living through another person's identity."
};
function renderPersonaForm(p,f,index){if(!f)return '<p>No form data available.</p>';return `<section class="persona-form-detail"><div class="persona-form-stage">Evolution ${index+1} · ${escapeHtml(f.stage)}</div><h2>${escapeHtml(f.name)}</h2><div class="persona-core-data"><div><strong>Arcana</strong><span>${escapeHtml(p.arcana)}</span></div><div><strong>Level</strong><span>${f.level==null?'—':`Lv. ${escapeHtml(f.level)}`}</span></div><div><strong>Affinity</strong><span>${escapeHtml(f.affinity||'—')}</span></div><div><strong>Weakness</strong><span>${escapeHtml(f.weakness||'—')}</span></div></div><section class="persona-origin"><h3>Origin</h3><p>${escapeHtml(personaOrigins[p.id]||'Story origin information will be added here.')}</p></section><div class="persona-skills">${skillGroup('Damage Skills',f.damageSkills)}${skillGroup('Support Skills',f.supportSkills)}${skillGroup('Passive Skills',f.passiveSkills)}${skillGroup('Unique / Special Skills',f.uniqueSkills,'unique')}</div></section>`;}
function renderPersonas(data){const selected=data.find(p=>p.id===currentId());if(selected)return renderPersonaDetail(selected);const cards=data.map(p=>`<article class="persona-card"><h2>${escapeHtml(p.name)}</h2><p><strong>Arcana:</strong> ${escapeHtml(p.arcana)}</p><p><strong>Character:</strong> ${escapeHtml(p.character)}</p><a href="personas/${encodeURIComponent(p.id)}.html">View Persona</a></article>`).join('');return `<div class="breadcrumb"><a href="../index.html">Home</a> <span>›</span> <strong>Personas</strong></div><h1>Main Personas</h1><p>Party Personas and their Royal evolution forms.</p><div class="persona-list">${cards}</div>`;}
function renderPersonaDetail(p){const forms=p.forms??[],initial=forms[0];const buttons=forms.map((f,i)=>`<button class="persona-form-button${i===0?' active':''}" type="button" data-persona-detail-form-index="${i}"><span>Evolution ${i+1}</span><strong>${escapeHtml(f.name)}</strong><small>${escapeHtml(f.stage)}</small></button>`).join('');return `<div class="breadcrumb"><a href="../../index.html">Home</a> <span>›</span> <a href="../personas.html">Personas</a> <span>›</span> <strong>${escapeHtml(p.name)}</strong></div><article class="persona-detail" data-persona-detail-id="${escapeHtml(p.id)}"><header class="persona-header"><p>Party Persona</p><h1 data-persona-detail-title>${escapeHtml(initial?.name||p.name)}</h1><p><strong>Arcana:</strong> ${escapeHtml(p.arcana)}</p><p><strong>Character:</strong> <a href="../characters/${encodeURIComponent(p.characterId)}.html">${escapeHtml(p.character)}</a></p></header><section class="persona-evolution-section"><h2>Evolution Path</h2><div class="persona-form-selector">${buttons}</div><div class="persona-selected-form" data-persona-detail-display>${renderPersonaForm(p,initial,0)}</div></section></article>`;}
function setupPersonaInteractions(target,data){target.querySelectorAll('[data-persona-detail-id]').forEach(card=>{const p=data.find(x=>x.id===card.dataset.personaDetailId);if(!p)return;const forms=p.forms??[],display=card.querySelector('[data-persona-detail-display]'),title=card.querySelector('[data-persona-detail-title]');card.querySelectorAll('[data-persona-detail-form-index]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.personaDetailFormIndex),f=forms[i];if(!f||!display)return;card.querySelectorAll('[data-persona-detail-form-index]').forEach((x,j)=>x.classList.toggle('active',j===i));display.innerHTML=renderPersonaForm(p,f,i);if(title)title.textContent=f.name;}));});}
export async function renderPage(page,target){if(!target||!pageMap[page])return;target.innerHTML=`<h1>${page[0].toUpperCase()+page.slice(1)}</h1><p>Loading data...</p>`;try{const data=await loadCollection(pageMap[page]);if(page==='confidants'){target.innerHTML=renderConfidants(data);setupConfidantInteractions(target,data);return;}if(page==='personas'){target.innerHTML=renderPersonas(data);setupPersonaInteractions(target,data);return;}if(page==='characters'){const personas=await loadCollection('personas');const enriched=data.map(c=>{const p=personas.find(x=>x.characterId===c.id);return {...c,personaId:c.personaId||p?.id||'',personaName:c.personaName||p?.name||'',personaRole:c.personaRole||`${p?.arcana||''} Persona`.trim()};});target.innerHTML=renderCharacterList(enriched);return;}target.innerHTML=`<h1>${page[0].toUpperCase()+page.slice(1)}</h1><pre>${escapeHtml(JSON.stringify(data,null,2))}</pre>`;}catch(error){target.innerHTML=`<h1>${page}</h1><p>Data connection error: ${escapeHtml(error.message)}</p>`;}}
